### ISSUE TITLE
Pull volley jar from mavenCentral.

### ISSUE THREAD

**Issue by krt16s** [kiall/android-tvheadend#1]
Why not use `compile 'com.mcxiaoke.volley:library:1.0.19'` or something like that for the volley.jar?

**Comment by kiall** [comment]
Generally, I prefer to not depend on 4th party builds of 3rd party libraries, I've no way of verifying the contents of that jar is good+safe - for all I know, it could have been modified to, for example, include a backdoor etc

(I'm not suggesting com.mcxiaoke.volley has anything wrong with it, simply that as a 4th party build - I have no mechanism available to verify it as trustworthy)

**Comment by kiall** [comment]
And - Apparently, following though to https://github.com/mcxiaoke/android-volley - Google has released a build of volley themselves on jCenter.

**Comment by kiall** [comment]
Fixed in https://github.com/kiall/android-tvheadend/commit/e67744789dc7e296e8a3493698aed54d8370c636
