### ISSUE TITLE
Exoplayer shrinking screen to 3/4 size

### ISSUE THREAD

**Issue by stevellion** [kiall/android-tvheadend#104]
When using exoplayer, the screen is shrunk by 1/4 over to the left hand side.
VLC displays OK.
![small-screen](https://cloud.githubusercontent.com/assets/839754/21614200/72d55b68-d1d0-11e6-9366-7394569e135a.jpg)

**Comment by UnsignedLong** [comment]
Just want to ACK this bug. Same here with Sony XD75 and matroska profile.

**Comment by stevellion** [comment]
I'm also on Sony XD75...

**Comment by kiall** [comment]
@UnsignedLong / @stevellion - Question, is this all channels? or only some?

could one of you update to v0.2.67, and gather the some logs for me?

https://gist.github.com/kiall/8c9da088956c9cbc2662921308cafee8 shows the logs I'm looking for, and the command to gather them once you have ADB connected to the TV. Ideally, gather the logs while changing from a working, to a squashed channel.

I suspect Sony isn't correctly handling "Pixel Aspect Ratio", where some broadcasters broadcast a squashed (width wise) image, and the receiving device has to un-squash it.

**Comment by kiall** [comment]
https://github.com/kiall/android-tvheadend/releases/tag/v0.2.67 has an APK download for 0.2.67, it's also uploaded to the Google Play Store...

**Comment by stevellion** [comment]
Seems to be all channels - I tried 4 Random, 2 x HD & 2 x SD. All the same with exoplayer.
VLC still OK.
[logcat.exo.txt](https://github.com/kiall/android-tvheadend/files/692534/logcat.exo.txt)

**Comment by kiall** [comment]
I just got the Sony 6.0 update for my TV, and still don't see this.. Can either of you check if A) you're on the latest firmware for your TV set, and B) if this is still happening with ExoPlayer?

**Comment by stevellion** [comment]
Yes, seems fixed on my version now too.  I'm not sure if I had an automatic update of the firmware, but it's working on v 2.81 - closing issue.

**Comment by stevellion** [comment]
This is still an issue if not using HTSP streaming. - low priority though and HTSP is default.

**Comment by kiall** [comment]
Since ExoPlayer+HTSP video is the only thing we'll be supporting going forward (the other choices will be removed soon), and since #146 is fixed, I'm going to close this out.
