### ISSUE TITLE
Chromecast support ?

### ISSUE THREAD

**Issue by lakano** [kiall/android-tvheadend#105]
Hello !

Thanks for your works!
Do you plan to support Chromecast please?
I have a tvheadend server on a Raspberry Pi2 and I searching a solution to cast tvheadend streams to my chromecast device.

Best regards,

**Comment by UnsignedLong** [comment]
andorid-tvheadend is the client for use on android-tv which have chromecast already enabled so this seems to be the wrong place for your question.
If you want to cast tvh channels to your chromecast you have to start the desired channel with a media player which support chromecast on your phone and than cast the (http) stream to your chromecast.

**Comment by lakano** [comment]
Ok, thanks !
