### ISSUE TITLE
Amazon Fire TV Compability

### ISSUE THREAD

**Issue by doe1097** [kiall/android-tvheadend#108]
Hi Kiall.
Are there any plans to make this little piece of gold working on an Amazon Fire TV? 
Best,
H.

**Comment by tunip** [comment]
If "Live Channels App" is available on Fire TV, you could try it.

**Comment by janwerner** [comment]
> If "Live Channels App" is available on Fire TV, you could try it.

It is not. Neither is the required API - [TV Input Framework](https://source.android.com/devices/tv/). 

Fire TV OS is based on Android Open Source Project (AOSP) (5.0/Lollipop if I remember correctly), but lacking all the Android TV components as well as Google Play Services.

**Comment by doe1097** [comment]
> Fire TV OS is based on Android Open Source Project (AOSP) (5.0/Lollipop if I remember correctly), but lacking all the Android TV components as well as Google Play Services.

That's correct. Amazon distributes its own modified version of Android called FireOS, but some apps are compatible anyways.

A missing PlayStore wouldn't be a problem for installation since sideloading is possible, but... after doing some Google, I see that the TVH Channels App is rather an extension for an existing app on Android TV than a standalone app... :-/

**Comment by kiall** [comment]
Yea, if Amazon has decided to ship an Android TV product without Androids TV Input Framework, there's not much I can do!

**Comment by chschafl** [comment]
Based on the information here: https://developer.amazon.com/docs/fire-tv/fire-os-6.html#devices-running-fire-os-6-versus-fire-os-5 .. do you think this might now work with the new Fire TV OS 6?

**Comment by doe1097** [comment]
> Based on the information here: https://developer.amazon.com/docs/fire-tv/fire-os-6.html#devices-running-fire-os-6-versus-fire-os-5 .. do you think this might now work with the new Fire TV OS 6?

For me it doesn't look like that Amazon is planning to implement the Android Live TV framework which this App relies on, so... I don't think so.

**Comment by chschafl** [comment]
From the article:

> Some of Nougat’s TV-specific features supported on Fire OS 6 include the following:
> 
> Picture in Picture (PiP): Allow users to pin a video to a corner of the screen while navigating to other areas in your app.
> Content Recording: Lets users record content on their TV, similar to a DVR.
> Time-shifting APIs: Lets users pause, rewind, or fast-forward live content.

Would this be sufficient?

**Comment by chschafl** [comment]
I've posted the question here as well: 
https://forums.developer.amazon.com/questions/91223/will-fire-os-6-supper-android-tv-live-channels-api.html
