### ISSUE TITLE
Initial setup failed to add account since v0.2.78/77

### ISSUE THREAD

**Issue by xi784** [kiall/android-tvheadend#136]
Hi Kiall,

since 0.2.78 im not able to create an account on fresh installed client.

Get Errormessage:
Failed to add account: Failed to validate HTSP Credentials.

Can anyone confirm?

greetz

**Comment by tunip** [comment]
I can confirm this issue. Same message on setup. After that I can still see the EPG. Only some channel icons are missing. Watching tv works.

**Comment by kiall** [comment]
I'll cut another release in a few mins with this fix.

**Comment by kiall** [comment]
v0.2.79 is now uploaded to the the play store..
