### ISSUE TITLE
Support for choosing the audio track

### ISSUE THREAD

**Issue by kiall** [kiall/android-tvheadend#14]
Support for choosing the audio track

**Comment by kiall** [comment]
Likely blocked on #5 for it to be done reliably.

**Comment by sajkat** [comment]
Does this mean where a channel has multiple audios - such as bbc - tvheadend streams the first channel which includes commentary and actually you want to set it to the second which is the one without commentary?

**Comment by seapoint** [comment]
You can set an Audio Filter in the Stream section of TVHeadend - worked for me as per the screenshot
![new bitmap image](https://cloud.githubusercontent.com/assets/1372635/20055630/ec3e5b90-a4d9-11e6-8111-8d590c03a64c.png)

**Comment by tunip** [comment]
I see this feature in selecting audio language per show like this:
![multiaudio](https://cloud.githubusercontent.com/assets/11404472/20055938/e9d459fe-a4e3-11e6-8d31-3784e6239753.jpg)

**Comment by seapoint** [comment]
I'm still on 6.0 with the nvidia shield - @tunip are you on 7.0?

**Comment by tunip** [comment]
@seapoint I am also on 6.0 with my nvidia shield. The screenshot is from a other project (not tvheadend).

**Comment by kiall** [comment]
It's half implement to various degrees for different session types, so some will show the choice, but nothing happens when you change..

**Comment by sajkat** [comment]
I have a MOI AMD Pro and it pushes both streams with and without commentary. Kodi i can set and force that choice for all channels forever never even thought to take it off @ tvheadend thanks @seapoint 

@kiall For me the switcher is there and works

**Comment by kiall** [comment]
Really? Maybe I did get it work on 1 of the 3 session choices (media player, VLC, exoplayer)... I thought I hadn't ;) either way, HTSP video is coming and replaces most if not all of that code!

**Comment by seapoint** [comment]
@tunip I hadn't considered VDR - and will more than likely stick with TVHeadend - for two reasons - because it works and because I would be kicked out of the living room if I start changing again. With the NAR audio filtered, I can use the webif to schedule & record, and (playback within PLEX at the moment) and I've finally got OSCAM working. I'm more than happy

**Comment by kiall** [comment]
Fixed in v0.1.66 on ExoPlayer session - ExoPlayer will soon become the only session choice, and this won't be implemented on the MediaPlayer or VLC session types. If there are specific issues with this feature on ExoPlayer, using a MKV stream profile, on v0.1.66, please open a new bug.
