### ISSUE TITLE
Support anamorphic source video

### ISSUE THREAD

**Issue by jasonpugsley** [kiall/android-tvheadend#15]
Anamorphic broadcasts (typically 1440x1080 and 720x576 in Australia) need to be scaled horizontally for display. I'm not sure if this is the right way but it works for me. Hardware/software scaling may be dependent on the hardware the app runs on.

    --- app/src/main/java/ie/macinnes/tvheadend/tvinput/DemoPlayerSession.java	(revision )
    +++ app/src/main/java/ie/macinnes/tvheadend/tvinput/DemoPlayerSession.java	(revision )
    @@ -204,7 +204,7 @@
                     TvTrackInfo.Builder builder = new TvTrackInfo.Builder(trackType, trackId);
    
                     if (trackType == DemoPlayer.TYPE_VIDEO) {
    -                    builder.setVideoWidth(format.width);
    +                    builder.setVideoWidth(Math.round(format.width * format.pixelWidthHeightRatio));
                         builder.setVideoHeight(format.height);
                     } else if (trackType == DemoPlayer.TYPE_AUDIO) {
                         builder.setAudioChannelCount(format.channelCount);

**Comment by kiall** [comment]
Interesting, have you tested this? I believe I previously hardcoded those width/height values to a sane resolution for content making use of display/pixel aspect ratios, and it had no effect on the video as displayed. All it did was cause the "720" icon to appear on the channel info overlay.

Either way, I'll give it a go and see how it looks.

**Comment by kiall** [comment]
v0.1.34 is now published to the Beta channel on the Play store, with this fix. Thanks!
