### ISSUE TITLE
App occasionally locks up, and a restart is required to start playback again

### ISSUE THREAD

**Issue by kiall** [kiall/android-tvheadend#150]
App occasionally locks up, and a restart is required to start playback again. I've seen this in dev/test, but not on my Shield.

Another user reports it happening after upgrades, and after his Mi Box resumes from sleep.

**Comment by kiall** [comment]
*Possibly* fixed by https://github.com/kiall/android-tvheadend/commit/be69c95a3c872b5d597b5723f58652f2943ebefa and https://github.com/kiall/android-htsp/commit/9be8852caf32afbdf9765b9b331c30c2008ac507

It's hard to know for sure though...

**Comment by stevellion** [comment]
Running 3.4 and saw a similar crash last night.. but more replicatable perhaps.
Switch to channel B > Multi audio.  I then selected the 2nd channel audio (English w/o narration)
Switch to channel A > no sound.  I think only 1 audio channel.  When attempting to bring up the audio select dialogue, the tvh client crashed. 
Switch to channel A> all fine again, but of course on 1st channel of audio.

**Comment by kiall** [comment]
So, I think every case this can happen has been fixed as of v0.3.12, please reopen if you still see this happening..
