### ISSUE TITLE
[Cleanup] Remove app link (if not needed)

### ISSUE THREAD

**Issue by tunip** [kiall/android-tvheadend#151]
Do we really need this app link? We start android-tvheadend through "Live Channels" app.

![grafik](https://cloud.githubusercontent.com/assets/11404472/23905115/5296f510-08ca-11e7-942f-683a4f239571.png)

**Comment by kiall** [comment]
There's, to my knowledge, no way to remove it and still be listed in the Play Store. That said, I've been meaning to make it open the preferences, so you don't need to do the whole setup just to get to them..

**Comment by tunip** [comment]
Open the preferences is fine. I asked because if you add the DVR feature another app link (DVR) will be added to this bar.
![grafik](https://cloud.githubusercontent.com/assets/11404472/23906236/a66fdb5e-08cd-11e7-9d73-2811abc091e0.png)
