### ISSUE TITLE
No image on TV screen

### ISSUE THREAD

**Issue by paramec** [kiall/android-tvheadend#155]
Hi.
TV screen is "black". Sound is working. 
I tried with different stream profiles from tvheadend (pass, htsp, webtv..), no image on the TV screen.
With other apps like kodi I have no problem, all the profiles are working very good.

I use tvheadend - Build: 4.1-2449~gda583493d
TV: Sony Bravia X80C series (https://www.sony.co.uk/electronics/televisions/x8005c-series).

2 weeks ago I had no problem. Is there a change made lately? 

The program is great and I really like to use it.

**Comment by xi784** [comment]
Since version 0.3.0. only htsp is still supported, on which version are you?

**Comment by paramec** [comment]
Version 0.2.88
Profile htsp set by default on server side (the old one was pass). 
htsp is set also on the TV side.
No improvement.

**Comment by xi784** [comment]
.88 is out since 6 days.
I would recommend to rerun setup. Check that ffmpeg audio is enabled and disable nvidia shield workaroundand htsp video.

**Comment by paramec** [comment]
I'd like to upgrade to 0.3.2 but there no new version in my app store. 
I also tried to subscribe to the beta versions and I have o privileges to do this.

**Comment by xi784** [comment]
you can find the latest build also here:
https://github.com/kiall/android-tvheadend/releases

you will need to copy the apk on a usb drive. As well you will need something like `es file explorer` for browsing and installing.

Subscribing to the beta may need some time until it will be available in the Play Store.

**Comment by tunip** [comment]
Second way, you could download the APK and sideload it to your device:
https://github.com/kiall/android-tvheadend/releases/download/v0.3.2/ie.macinnes.tvheadend_v0.3.2-release.apk

**Comment by paramec** [comment]
Ok, I made the upgrade. No image. Sound only.

**Comment by kiall** [comment]
When your playing, can you check the TVHeadend UI, Status Tab, then Subscriptions tab, what profile does it show the subscription using? It should show "HTSP".

Then, can you check the service info for the channel, also in the UI, to see the list if streams in the channel - what video codec is the channel?

**Comment by kiall** [comment]
Also, some logs from the device would be great!

**Comment by paramec** [comment]
The profile is htsp in the UI.
I tried several type of channels, the same issue. 
I disabled also passthrough (#156) and nVidia shield.
I have a log from my TV as you showed to me how to do it (thank you).
[logSony.txt](https://github.com/kiall/android-tvheadend/files/853612/logSony.txt)

I installed the latest version (0.3.4) but still no improvement on my issue.

**Comment by paramec** [comment]
Hello again. 
I found the reason of the reported issue. I made an activation of  the lock channels with pin code. From TV settings. I remove it and now all the channels are back with video. How this is affecting the tvheadend client, I don't know. 
If there is a need for more debug I can support , just let me know.

**Comment by kiall** [comment]
Ah, if the channel is pin locked (which is I think a Sony specific feature), I have no idea how it might behave.My Sony doesn't appear to have this feature, so I can't test this out.. As you found the issue, and it's not directly this app, I'll close this out.
