### ISSUE TITLE
nVidia Shield TV (2017) fails to render video/audio with Audio passthrough enabled

### ISSUE THREAD

**Issue by willeh1** [kiall/android-tvheadend#156]
Since after v.30 (possibly in v.33 onwards) if the Audio Passthrough option is enabled audio and video fail to render.

Logs attached with a couple of channel changes

[ShieldPassthruENABLED.zip](https://github.com/kiall/android-tvheadend/files/852703/ShieldPassthruENABLED.zip)

**Comment by kiall** [comment]
Ugh, looks like your logs got "busted" by hitting a bug that I (hope) I finally fixed in v0.3.3. Could you give it another shot?

Once that issue occurs, as it did on your first attempt to tune to a channel in those logs, there's nothing useful logged :(

**Comment by kiall** [comment]
Possibly related to #155 - even though that presents different symptoms (Yes audio, No video)

**Comment by willeh1** [comment]
I've tried replicating this four or five times now and I'm unable to get the same behavior - it seems with the option enabled or disabled this now works, the previous log is the only working attempt i've had where it fails to load and had logging enabled.

I briefly compared the two (working and not working) and found i didn't get any of the below in my working logs - if i get it broken again i'll happily reapply logging;

03-18 19:44:12.909  3444  4889 E LoadTask: Unexpected exception loading stream
03-18 19:44:12.909  3444  4889 E LoadTask: java.lang.NullPointerException: Attempt to invoke virtual method 'int ie.macinnes.htsp.HtspMessage.getInteger(java.lang.String, int)' on a null object reference
03-18 19:44:12.909  3444  4889 E LoadTask: 	at ie.macinnes.htsp.tasks.Subscriber.subscribe(Subscriber.java:132)
03-18 19:44:12.909  3444  4889 E LoadTask: 	at ie.macinnes.htsp.tasks.Subscriber.subscribe(Subscriber.java:102)
03-18 19:44:12.909  3444  4889 E LoadTask: 	at ie.macinnes.tvheadend.player.HtspDataSource.open(HtspDataSource.java:99)
03-18 19:44:12.909  3444  4889 E LoadTask: 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:623)
03-18 19:44:12.909  3444  4889 E LoadTask: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
03-18 19:44:12.909  3444  4889 E LoadTask: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
03-18 19:44:12.909  3444  4889 E LoadTask: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-18 19:44:12.909  3444  4889 E LoadTask: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-18 19:44:12.909  3444  4889 E LoadTask: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-18 19:44:12.909  3444  4889 E LoadTask: 	at java.lang.Thread.run(Thread.java:761)

**Comment by kiall** [comment]
Yea, above that in your logs, I'm seeing this:

    03-18 19:43:36.648  3444  4873 E HtspConnection: Something failed - shutting down
    03-18 19:43:36.648  3444  4873 E HtspConnection: java.util.ConcurrentModificationException
    03-18 19:43:36.648  3444  4873 E HtspConnection: 	at java.util.ArrayList$Itr.next(ArrayList.java:831)
    03-18 19:43:36.648  3444  4873 E HtspConnection: 	at ie.macinnes.htsp.HtspMessageDispatcher.onMessage(HtspMessageDispatcher.java:179)
    03-18 19:43:36.648  3444  4873 E HtspConnection: 	at ie.macinnes.htsp.HtspDataHandler.read(HtspDataHandler.java:115)
    03-18 19:43:36.648  3444  4873 E HtspConnection: 	at ie.macinnes.htsp.HtspConnection.processReadableSelectionKey(HtspConnection.java:303)
    03-18 19:43:36.648  3444  4873 E HtspConnection: 	at ie.macinnes.htsp.HtspConnection.run(HtspConnection.java:226)
    03-18 19:43:36.648  3444  4873 E HtspConnection: 	at java.lang.Thread.run(Thread.java:761)

Once that happens, all bets are off until a reboot.

I'm pushing another change (https://github.com/kiall/android-tvheadend/commit/be69c95a3c872b5d597b5723f58652f2943ebefa and https://github.com/kiall/android-htsp/commit/9be8852caf32afbdf9765b9b331c30c2008ac507) that will without a doubt prevent that error... I'll push a another build to the store with those soon.

**Comment by kiall** [comment]
v0.3.4 fixes that ConcurrentModificationException, which would have randomly occurred, and prevented any audio / video from working.

**Comment by willeh1** [comment]
So far I've been unable to replicate the behaviour with no audio or picture in 0.3.4, testing continues...

**Comment by kiall** [comment]
Excellent, hopefully it was just that ConcurrentModificationException :) Going to close this out, reopen if it happens again!
