### ISSUE TITLE
A colorful narrow band has appeared on right side of the screen

### ISSUE THREAD

**Issue by schneci** [kiall/android-tvheadend#158]
Hi,

I'm using the KDL-43W805C Sony Bravia Android TV. I have instaled the 
Tvheadend Live Channel (BETA) v. 2.88 (13-03-2017) version.

I connected the Libreelec8.0.1 mediaplayer with tvheadend 4.2 and I used the **pass** profile in above tvheadend live channel plugin, but a colorful narrow band has appeared on right side of the screen

What is the wrong: TVH or the client configuration?

**Comment by kiall** [comment]
I had this for a while on a Sony 2015 too, however, it turned out to be an issue with the DVB tuner driver.. After upgrading, the band went away.

Do you have any other clients you can test in?

**Comment by schneci** [comment]
Thank you for answer!
It seems it works well when receiving HD broadcasts, but the band will appear when an SD channel. The DVB tuner driver runs the tvheadenden. The question is, which of DVB device driver to be updated, or are you understand that Sony TV video driver needs to be updated?

**Comment by kiall** [comment]
For me, it was the DVB card driver on my TVHeadend server. Once updated, the band disappeard

**Comment by kiall** [comment]
Closing as more info is needed, and none provided yet. Please reopen if you're still seeing this issue.
