### ISSUE TITLE
"the video is unexpectedly unavailable"

### ISSUE THREAD

**Issue by habr05** [kiall/android-tvheadend#159]
Hi there,

Running v3.4 on Nvidia Shield with tvheadend v4.1-2355~g1dd2652. TVHE has a mix of ATSC and IPTV feeds. Few of the streams play for 1-2 seconds and video drops with "The video is unexpectedly unavailable". Some of them come back to live after flipping channels back & forth, some do not. What gives?

PS
Kodi's TVHE client is working fine with current configuration/lineup. 

Cheers,
David

[logcat.txt](https://github.com/kiall/android-tvheadend/files/888257/logcat.txt)

**Comment by habr05** [comment]
Update: some ATSC channels give the same error. Restarting Live TV seems to clear/restore ATSC channels but not the IPTV sources in original post.

[logcat-1.txt](https://github.com/kiall/android-tvheadend/files/888260/logcat-1.txt)

**Comment by habr05** [comment]
More testing and more information. 

Did a fresh install of Tvheadend v4.1-2355~g1dd2652 and configured HDHomeRun Connect as an input. No other IPTV/ATSC configured, just HDHomeRun. Did a fresh install of v3.4 app. To make troubleshooting easier, configuration and settings changes are either minimal and/or stock.

Tested flipping (changing) between 6 ATSC channels. At random times random channels will go blank. Fliping (one or more times) up/down from the channel will bring it back. Looking at TVHE server logs I see following:

`2017-04-04 14:36:35.864 subscription: 002A: "127.0.0.1 [ shield | android-tvheadend (TV) ]" subscribing on channel "CBC", weight: 150, adapter: "HDHomeRun ATSC-T Tuner #1 (192.168.11.133)", network: "ATSC-T Network", mux: "515MHz", service: "CALGARY CBRT-DT", profile="htsp", hostname="127.0.0.1", username="shield", client="android-tvheadend (TV)"

2017-04-04 14:36:35.864 subscription: 0029: "127.0.0.1 [ shield | android-tvheadend (TV) ]" unsubscribing from "Global", hostname="127.0.0.1", username="shield", client="android-tvheadend (TV)"

2017-04-04 14:36:36.788 subscription: 002A: "127.0.0.1 [ shield | android-tvheadend (TV) ]" unsubscribing from "CBC", hostname="127.0.0.1", username="shield", client="android-tvheadend (TV)"`

Looking at the logcat (attached) I see IOException at "04-04 14:36:36.787". 

`04-04 14:36:36.787  3574  3574 D ie.macinnes.tvheadend.tvinput.BaseSession: Session onSetCaptionEnabled: false (1)
04-04 14:36:36.787  3574  5611 W ie.macinnes.tvheadend.player.HtspExtractor: Caught IOException, returning RESULT_END_OF_INPUT
04-04 14:36:36.787  3574  5611 W ie.macinnes.tvheadend.player.HtspExtractor: java.io.EOFException
04-04 14:36:36.787  3574  5611 W ie.macinnes.tvheadend.player.HtspExtractor: 	at java.io.ObjectInputStream$BlockDataInputStream.readFully(ObjectInputStream.java:2750)
04-04 14:36:36.787  3574  5611 W ie.macinnes.tvheadend.player.HtspExtractor: 	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1688)
04-04 14:36:36.787  3574  5611 W ie.macinnes.tvheadend.player.HtspExtractor: 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1345)
04-04 14:36:36.787  3574  5611 W ie.macinnes.tvheadend.player.HtspExtractor: 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
04-04 14:36:36.787  3574  5611 W ie.macinnes.tvheadend.player.HtspExtractor: 	at java.util.HashMap.readObject(HashMap.java:1469)
04-04 14:36:36.787  3574  5611 W ie.macinnes.tvheadend.player.HtspExtractor: 	at java.lang.reflect.Method.invoke(Native Method)
04-04 14:36:36.787  3574  5611 W ie.macinnes.tvheadend.player.HtspExtractor: 	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1006)
04-04 14:36:36.787  3574  5611 W ie.macinnes.tvheadend.player.HtspExtractor: 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1894)
04-04 14:36:36.787  3574  5611 W ie.macinnes.tvheadend.player.HtspExtractor: 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1799)
04-04 14:36:36.787  3574  5611 W ie.macinnes.tvheadend.player.HtspExtractor: 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
04-04 14:36:36.787  3574  5611 W ie.macinnes.tvheadend.player.HtspExtractor: 	at java.io.ObjectInputStream.readUnshared(ObjectInputStream.java:463)
04-04 14:36:36.787  3574  5611 W ie.macinnes.tvheadend.player.HtspExtractor: 	at ie.macinnes.tvheadend.player.HtspExtractor.read(HtspExtractor.java:114)
04-04 14:36:36.787  3574  5611 W ie.macinnes.tvheadend.player.HtspExtractor: 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:635)
04-04 14:36:36.787  3574  5611 W ie.macinnes.tvheadend.player.HtspExtractor: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
04-04 14:36:36.787  3574  5611 W ie.macinnes.tvheadend.player.HtspExtractor: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
04-04 14:36:36.787  3574  5611 W ie.macinnes.tvheadend.player.HtspExtractor: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-04 14:36:36.787  3574  5611 W ie.macinnes.tvheadend.player.HtspExtractor: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
04-04 14:36:36.787  3574  5611 W ie.macinnes.tvheadend.player.HtspExtractor: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
04-04 14:36:36.787  3574  5611 W ie.macinnes.tvheadend.player.HtspExtractor: 	at java.lang.Thread.run(Thread.java:761)
04-04 14:36:36.787  3574  5611 I ie.macinnes.tvheadend.player.HtspDataSource: Closing HTSP DataSource
04-04 14:36:36.787  3574  5611 I Subscriber: Requesting unsubscription from channel 1221380995`

That particular channel (CBC), looking at "Status > Stream" in TVHE server, has SNR ~85% and Signal Strenght ~95%.

Let me know if more info is needed.

Cheers,
David

**Comment by habr05** [comment]
Tested Tvheadend.apk (Tvheadend 4.1-2481~g8047f4f-dirty) for Shield - similar results.

**Comment by kiall** [comment]
In theory, e7083814b75e4102e62b7d2de1f3e89a49f19355 will fix this and is included in v0.3.5 (which will be on the github releases in a few mins, and the play store in the next few hours)

**Comment by kiall** [comment]
I'm going to hit close, re-open if it comes back with 0.3.5+
