### ISSUE TITLE
Tvheadend Live Cannel loses frame sequence number

### ISSUE THREAD

**Issue by schneci** [kiall/android-tvheadend#162]
If the received channel stream is damaged (temporally some i-frame drops out), the picture begins to stutter until I switch the cahnnel back and forth. After this the broadcast is correct.

I think the app loses the frame sequence number and the switching of channel is reset of it.

**Comment by kiall** [comment]
What device are you on?

Typically, after a short+temporary signal loss, I've seen the app recover and work just fine. I'm wondering if this is possibly a device specific issue.

Ideally, of you could grab some logs from the device as it happens, that would help identify.

**Comment by schneci** [comment]
I'm using a TBS-5281 DVB-C dual adapter tuner with TVheadend-4.2 with kodi 17.1in Librelec 8.0 environment. If some short transient coaxial line problem is disrupted the stream the quality of broadcast will not return to the original level, and the screen freezes periodically in TVheadend Live channel App on Sony TV.
If I switch back and forth the channel it will be restored the original image quality. This problem does not occur if I'm watching the TV channel trough Kodi.

Ok, if this will be happened, I will try to send the log messages of Tvheadend.

**Comment by kiall** [comment]
Please reopen if you can gather the requested logs, thanks!
