### ISSUE TITLE
Instability after resume from standby

### ISSUE THREAD

**Issue by gallivanter** [kiall/android-tvheadend#163]
This could be two separate bugs or related. Sometimes, usually after putting the Shield into standby and then resuming, either the video or the entire stream fails to resume correctly.

First repro (video fails):
1. Start streaming in Live Channels
2. Whilst streaming, place Shield into Standby
3. Bring Shield out of Standby
4. Audio continues but video is black. Overlays function, can navigate out of Live Channels and back in. Channel can be changed but video is always black.

Second repro (stream fails):
1. Start streaming in Live Channels
2. After bringing device back from Standby, changing channels quickly, etc, the stream fails to play with an error "The video is unexpectedly unavailable".

Workarounds:
- Switching in and out of Live Channels app sometimes causes some sort of refresh that resolves first repro, bringing video back.
- Force stopping Live Channels and relaunching usually resolves both issues.
- Sometimes forcing disconnection of client streams from TVH helps (Live Channels appears to keep streams alive even when nothing is playing).

Specs:
- Nvidia Shield 16GB (original) running FW 5.1
- Denon AVR-X3200W AV Receiver
- LG LD920 TV
- Triax TSS 400 MkII
- TVH 4.1-2533~g80c52b2 running on Debian Jessie
- Latest FW on all devices, attempted factory resets on each device in chain including Shield.
- Network connected via GbE, A/V via HDMI.

These issues are intermittent and are usually induced by some stressful conditions, such as quick channel switching, bringing the device in and out of standby, etc. The interesting thing is that even once the stream completely fails, TVH still sees an active connection to the Shield. If I force disconnect the Shield from TVH it just reconnects instantly, even though nothing is playing.

Update: Unable to reproduce the above issues using Kodi on the Shield streaming from TVH.

**Comment by kiall** [comment]
Sorry, been a while since I had a chance to work on the app.. I'll try each reproduction you gave today and see what I come up with.

**Comment by kiall** [comment]
I've tried both of these on my shield, using v0.3.12, and neither reproduces.

Some changes landed that are likely to have fixed this, can you give that release a go and let me know if you're still seeing these issues?

**Comment by gallivanter** [comment]
Sorry for the delay in response, I haven't had any time to test until now. I'm now on v0.3.15 and having no issues with stability. Shield also updated to FW5.2 and TVH to 4.3-221. This can be closed. Thanks for your hard work! (:
