### ISSUE TITLE
Video is unexpectedly unavailable

### ISSUE THREAD

**Issue by justinbyoung** [kiall/android-tvheadend#164]
I have haystack.tv set up as a second Live Channels source. If I play a haystack channel I am then unable to play a TV Headend channel, I get a "The video is unexpectedly unavailable" message. It will sometimes play the first few seconds of the first tvheadend channel, but then it stops. Changing channel just gives a black image from then on. I have the same issue on both my Shield TV and a Xiaomi Mibox. A reboot seems to be the only way to get Live Channels working again.

[logcat.txt.zip](https://github.com/kiall/android-tvheadend/files/938936/logcat.txt.zip)

**Comment by kiall** [comment]
Okay, I can see part of what's happening from this log and am guessing a little at the rest, the subscription is taking longer than a second to start, we're timing out, and not handling the error condition.

I'm curious about your setup, and why it's taking so long to subscribe to a channel?

**Comment by justinbyoung** [comment]
What do you need to know? Server or client setup? I am assuming server.

Server details
Ubuntu 16.04
HTS Tvheadend 4.2.1-1~g658ddd6 (just upgraded but was having the same issue with 4.1)

What other details would you like?

I have two clients, a Shield TV and  Xiaomi Mibox. Both have the same issue.

**Comment by justinbyoung** [comment]
I just found that by Force Stopping tvheadend on the client I can get Live Channels working without rebooting.

**Comment by justinbyoung** [comment]
I have reverted to 0.3.6 for the moment and that version is working fine.

**Comment by kiall** [comment]
Given 0.3.6 works, I suspect this and #165 are the same issue.

**Comment by kiall** [comment]
Going to close this one in flavor of #165 as more conversation has happened over there
