### ISSUE TITLE
Error - This video is unexpectedly unavailable

### ISSUE THREAD

**Issue by breezytm** [kiall/android-tvheadend#202]
Hey, 

Recently joined the community as well as this app and I must say it works fairly well. I do get this error "this video is unexpectedly unavailable" every time I tune to a channel. However the channel does work a few seconds later.

**Comment by breezytm** [comment]
My best guess is this is a time out error. The green HDHR View App used to do the same thing as well when integrated with Live Channels. They were able to fix it in the grey app. I am wondering if this can be fix in TVHeadEnd app as well.

**Comment by 9point6** [comment]
I've experienced this also.

**Comment by tunip** [comment]
This happens since the the latest update to Googles "Live Channels" app.  Something changed there.

**Comment by breezytm** [comment]
Perphas a communication channel between Live Channels and TVH is need to keep things from breaking when they decide to make changes.

**Comment by kiall** [comment]
@breezytm I'd love one, but Google don't tend to do that :)

Anyway, I updated Live Channels yesterday and have started to see this too - will find a fix over the weekend!

**Comment by breezytm** [comment]
@kiall Thank you for looking into it.

**Comment by kiall** [comment]
This should be fixed in the current beta build, which will rollout to everyone on the play store soon.

**Comment by breezytm** [comment]
I am using the DVR build. I don't believe it is the same as the beta in the store. How would I get the update?

**Comment by xi784** [comment]
http://jenkins.macinnes.ie/job/android-tvheadend/job/develop/23/

**Comment by breezytm** [comment]
I figured. Just wanted to make sure. Thanks.
