### ISSUE TITLE
Wrong EPG time

### ISSUE THREAD

**Issue by Marcinbar** [kiall/android-tvheadend#219]
Client use time from the device. When time on device is wrong then you can see "no title" in epg.

Maybe client  should use time from the server. I am found getSysTime methods to do this on this site https://tvheadend.org/projects/tvheadend/wiki/Htsp

**Comment by kiall** [comment]
We can't correct the time on the device, or use a different reference clock for displaying EPG data, is there a reason the clock on the device can't be set correctly? It seems like this would fix this issue, and probably issues with other apps too?

**Comment by Marcinbar** [comment]
When i set time and date manualy then is fine. 
When device set correct time and date from server ntp then is fine.
But when i reboot device without internet connection clock reset to default (01.01.2015 01:00am) then epg does not display correctly data.

Server and client is the same device.

**Comment by kiall** [comment]
There's really nothing I can do here, I tell Android what time the program is on, and Android shows it at the right time, I don't have the ability to offset this when your clock is wrong, or sync it to tvheadend's clock.

If your devices clock is wrong, you should fix the clock! If the device doesn't keep the time after a reboot, you should file a bug with the manufacturer - I can't fix that (I know, the chances of that actually getting a fix are slim to none, but there really is nothing I can do on this side!)
