### ISSUE TITLE
Import channeltags or contenttype (genre) from Tvheadend as TIF channelgroups

### ISSUE THREAD

**Issue by kiall** [kiall/android-tvheadend#22]
Import channeltags or contenttype (genre) from Tvheadend as TIF channelgroups,

Reported here: https://plus.google.com/103039730249812922520/posts/NranWJn3uuJ

**Comment by tunip** [comment]
Tvheadend channeltags/bouquets can not be used in Live Channels. Only  program genres are possible at the moment.
https://developer.android.com/reference/android/media/tv/TvContract.Programs.Genres.html

As we use HTSP EPG, another htsp message field "contentType" in BaseEventResponse.java is needed.

Genres could be found here:
http://www.etsi.org/deliver/etsi_en/300400_300499/300468/01.11.01_60/en_300468v011101p.pdf (page 40)

Example genres:
```
0x1 0x0 movie/drama (general) -> 0x10
0x1 0x1 detective/thriller -> 0x11
0x1 0x2 adventure/western/war -> 0x12
0x1 0x3 science fiction/fantasy/horror -> 0x13
0x1 0x4 comedy -> 0x14
...
```

Maybe the Tvheadend "contentType" value needs to be converted to something readable for TIF.

Snippet:
```
if (mContentType != null && mContentType.length > 0) {
            values.put(TvContract.Programs.COLUMN_CANONICAL_GENRE,
                    TvContract.Programs.Genres.encode(mContentType));
        } else {
            values.putNull(TvContract.Programs.COLUMN_CANONICAL_GENRE);
        }
```

**Comment by tunip** [comment]
If I find time this weekend, I can try to implement this.

**Comment by tunip** [comment]
First step is done.
![img_20161110_195602](https://cloud.githubusercontent.com/assets/11404472/20189978/d0854834-a77f-11e6-9fc1-9a988919efad.jpg)

The assignment needs to be improved. And multiple genres per event are not considered.

**Comment by tunip** [comment]
Here is the list of the Tvheadend contentType ids.

```
	Movie/Drama:
16	movie/drama (general)
17	detective/thriller
18	adventure/western/war
19	science fiction/fantasy/horror
20	comedy
21	soap/melodrama/folkloric
22	romance
23	serious/classical/religious/historical movie/drama
24	adult movie/drama
25	to 0xE reserved for future use
31	user defined
	
	News/Current affairs:
32	news/current affairs (general)
33	news/weather report
34	news magazine
35	documentary
36	discussion/interview/debate
37	to 0xE reserved for future use
47	user defined
	
	Show/Game show:
48	show/game show (general)
49	game show/quiz/contest
50	variety show
51	talk show
52	to 0xE reserved for future use
63	user defined
	
	Sports:
64	sports (general)
65	special events (Olympic Games, World Cup, etc.)
66	sports magazines
67	football/soccer
68	tennis/squash
69	team sports (excluding football)
70	athletics
71	motor sport
72	water sport
73	winter sports
74	equestrian
75	martial sports
76	to 0xE reserved for future use
79	user defined
	
	Children's/Youth programmes:
80	children's/youth programmes (general)
81	pre-school children's programmes
82	entertainment programmes for 6 to14
83	entertainment programmes for 10 to 16
84	informational/educational/school programmes
85	cartoons/puppets
86	to 0xE reserved for future use
95	user defined 

	Music/Ballet/Dance:
96	music/ballet/dance (general)
97	rock/pop
98	serious music/classical music
99	folk/traditional music
100	jazz
101	musical/opera
102	ballet
103	to 0xE reserved for future use
111	user defined
	
	Arts/Culture (without music):
112	arts/culture (without music, general)
113	performing arts
114	fine arts
115	religion
116	popular culture/traditional arts
117	literature
118	film/cinema
119	experimental film/video
120	broadcasting/press
121	new media
122	arts/culture magazines
123	fashion
124	to 0xE reserved for future use
127	user defined
	
	Social/Political issues/Economics:
128	social/political issues/economics (general)
129	magazines/reports/documentary
130	economics/social advisory
131	remarkable people
132	to 0xE reserved for future use
143	user defined
	
	Education/Science/Factual topics:
144	education/science/factual topics (general)
145	nature/animals/environment
146	technology/natural sciences
147	medicine/physiology/psychology
148	foreign countries/expeditions
149	social/spiritual sciences
150	further education
151	languages
152	to 0xE reserved for future use
159	user defined
	
	Leisure hobbies:
160	leisure hobbies (general)
161	tourism/travel
162	handicraft
163	motoring
164	fitness and health
165	cooking
166	advertisement/shopping
167	gardening
168	to 0xE reserved for future use
175	user defined 
```

**Comment by kiall** [comment]
The core of was this was fixed in #90 - If there are specific additions etc, lets open a new+more specific bug :)

**Comment by xi784** [comment]
@tunip 
is contentType/category import via tv_grab_wg++>xmltv>tvheadend working for you?
i take a look into guide.xml, category via horizon.tv is catched, but tvheadend didnt import.

**Comment by xi784** [comment]
https://tvheadend.org/boards/12/topics/301

I think that is the problem..

**Comment by tunip** [comment]
@xi784 yes it works fine. But I replace in the xmltv file every category for each event with an ETSI conform genre. For this task i have a simple shell script.

Example:
```
#!/bin/bash

# Define all ETSI genres
MOVIE=$"Movie/Drama"
THRILLER=$"Detective/Thriller"
ADVENTURE=$"Adventure/Western/War"
...

# Map xmltv genre to ETSI genre
declare -A ARRAY
ARRAY["Abenteuer"]=$ADVENTURE
ARRAY["Action"]=$ADVENTURE
...

REGEX_PRE=$'<category[^>]*>'
REGEX_POST=$'</category>'

for K in "${!ARRAY[@]}"; do
  REGEX=$REGEX_PRE$K$REGEX_POST
  SUSTI='<category lang="en">'${ARRAY[$K]}'</category>'
  sed -r -i "s|$REGEX|$SUSTI|" /mnt/cache/appdata/tvheadend/data/xmltv/guide.xml
done
```

**Comment by xi784** [comment]
Bin einen anderen Weg gegangen, aber der Ansatz ist der gleiche 💃 

über die ini gegangen und arbeite mit category.modify - selbes Resultat, aber vielen dank 👍

**Comment by tunip** [comment]
Magst deinen category.modify Teil aus deiner ini teilen? Der Ansatz gefällt mir.

**Comment by xi784** [comment]
Erster Entwurf für die horizon.tv.de

category.modify {replace|Drama (serie)|soap/melodrama/folkloric}
category.modify {replace|Drama (film)|movie/drama (general)}
category.modify {replace|Komödie|comedy}
category.modify {replace|Sci Fi|science fiction/fantasy/horror}
category.modify {replace|Horror|science fiction/fantasy/horror}
category.modify {replace|Thriller|detective/thriller}
category.modify {replace|Action|adventure/western/war}
category.modify {replace|Abendteuer|adventure/western/war}
category.modify {replace|Melodram|soap/melodrama/folkloric}
category.modify {replace|Krimi|detective/thriller}
category.modify {replace|Fantasie|science fiction/fantasy/horror}
*
category.modify {replace|Nachrichten|news/current affairs (general)}
category.modify {replace|Wetter|news/weather report}
category.modify {replace|Dokumentation|documentary}
category.modify {replace|Bildung|education/science/factual topics (general)}
category.modify {replace|Weiterbildung|education/science/factual topics (general)}
category.modify {replace|Soziales|social/spiritual sciences}
category.modify {replace|Politik|social/political issues/economics (general)}
category.modify {replace|Wirtschaft|economics/social advisory}
category.modify {replace|Wissen|technology/natural sciences}
category.modify {replace|Magazin|magazines/reports/documentary}
category.modify {replace|Talk|discussion/interview/debate}
category.modify {replace|Talk Show|talk show}
category.modify {replace|Natur|nature/animals/environment}
category.modify {replace|Gesundheit|fitness and health}
category.modify {replace|Medizin|medicine/physiology/psychology}
*
category.modify {replace|Show|show/game show (general)}
category.modify {replace|Unterhaltungsshow|game show/quiz/contest}
category.modify {replace|Kochen|cooking}
category.modify {replace|Reisen|tourism/travel}
category.modify {replace|Freizeit|leisure hobbies (general)}
category.modify {replace|Lifestyle|arts/culture (without music, general}
category.modify {replace|Religion|religion}
category.modify {replace|Shopping|advertisement/shopping}
category.modify {replace|Mode|fashion}
*
category.modify {replace|Musik|music/ballet/dance (general)}
category.modify {replace|Tanz|music/ballet/dance (general)}
category.modify {replace|Volksmusik|folk/traditional music}
category.modify {replace|Rock|rock/pop}
category.modify {replace|Pop|rock/pop}
category.modify {replace|Klassik|serious music/classical music}
category.modify {replace|Musical / Oper|musical/opera }
category.modify {replace|Jazz|jazz}
category.modify {replace|Ballet|ballet}
*
category.modify {replace|Sport Magazin|sports magazines}
category.modify {replace|Fussball|football/soccer}
category.modify {replace|Sport|sports (general)}
category.modify {replace|Teamsport|team sports (excluding football)}
category.modify {replace|Tennis|tennis/squash}
category.modify {replace|Motorsport|motor sport}
category.modify {replace|Leichtahtletik|athletics}
*
category.modify {replace|Kunst|arts/culture (without music, general)}
category.modify {replace|Kunst Magazin|arts/culture magazines}
category.modify {replace|Bildende Kunst|performing arts}
category.modify {replace|Kultur|arts/culture (without music, general)}
*
category.modify {replace|Kinder|pre-school children's programmes}
category.modify {replace|Jugend|children's/youth programmes (general)}
category.modify {replace|Kinder, 6 14|entertainment programmes for 6 to14}
category.modify {replace|Kinder, 10 16|entertainment programmes for 10 to 16}

Grüße :)

**Comment by xi784** [comment]
Sieht eigentlich alles ganz vielversprechend aus.. verzeihe mir wenn noch nicht jede Kategorie entsprechend passend wirkt. 🥇
