### ISSUE TITLE
Does not work after TVheadend version 6cd24666 released 2017-11-09 and newer

### ISSUE THREAD

**Issue by Vispen74** [kiall/android-tvheadend#225]
Since the TVheadend upgraded to unstable version 4.3 6cd24666 and newer, the Live Channel app no longer works. Run the setup again, but no luck. Running TVheadend on Ubuntu Server, Live Channel app on Sony Bravia with Android-TV 6.0.

**Comment by xi784** [comment]
Use stable release 4.2.4~ for Live Channels App.

I think kiall paused developing for the moment - there are some changes at epg handling in tvheadend testing repo.

**Comment by Vispen74** [comment]
Okej thanks, I´ll try stable then.

2017-11-10 21:48 GMT+01:00 Dominik <notifications@github.com>:

**Comment by Vispen74** [comment]
It wasn´t that easy to roll back TVheadend back-end to 4.2 Stable, I can´t get it to work without re-do all the configuration. I rolled back to Unstabe 4.3 3d2300e3 2017-11-08 10:12, seems to work.

**Comment by Vispen74** [comment]
Changed to Tvheadend 4.2 stable build, works OK now. Closing this ticket.
