### ISSUE TITLE
Update ExoPlayer to 2.7.x

### ISSUE THREAD

**Issue by TheDiamondPicks** [kiall/android-tvheadend#244]
Hi,

Is it possible for ExoPlayer to be updated to a later version? I would quite like to be able to use some of the newer ExoPlayer API methods (mostly #createMessage), as a part of implementing #242. I managed to get it compiling and running live channels with using a newer ExoPlayer version from Google's maven repo, but I encountered some issues (Abstract errors), which I have put down to the mismatch between the ExoPlayer and FFmpeg extension versions (based on a brief google search).

As Google does not provide FFmpeg libraries, and that the only linux box I have is a server which I don't want to clutter with the android SDK, are we able to get an upgrade to ExoPlayer pushed to bintray?

(If this issue better belongs in https://github.com/kiall/exoplayer, feel free to close it, I can repost it if needed).

Thanks,

**Comment by kiall** [comment]
I've built ExoPlayer 2.7.1 and uploaded to BinTray, however I've not checked they work :) If you have the time, it would be great to get a PR that updates us (ideally, separate from the implementation of #242 to keep it easier to review and merge!)

https://bintray.com/kiall/exoplayer

**Comment by TheDiamondPicks** [comment]
#245
