### ISSUE TITLE
Discard S0 E0 metadata

### ISSUE THREAD

**Issue by kiall** [kiall/android-tvheadend#25]
Discard S0 E0 metadata.

Reported on G+ here: https://plus.google.com/103039730249812922520/posts/4qyMANvL59d

**Comment by tunip** [comment]
Only set seasonNumber if we have one, e.g., many documentation shows only have episode numbers like this.

(right now, this events has all a season of 0 in Live Channles):
![image](https://cloud.githubusercontent.com/assets/11404472/17296251/84a313fc-5800-11e6-8956-a9b10c6d42bd.png)

Minor improvment if you have events without a season number, only show episodeNumber:
```
        if (clientEvent.seasonNumber != 0) {
            program.setSeasonDisplayNumber(Integer.toString(clientEvent.seasonNumber));
        }
		if (clientEvent.episodeNumber != 0) {
            program.setEpisodeDisplayNumber(Integer.toString(clientEvent.episodeNumber));
        }
```
Thx

**Comment by kiall** [comment]
@tunip This feels like one of those things where we just can't fix all the possibilities.. Since S0E1, S0E2 is a common pattern for naming "specials" (e.g. between season episodes etc), where the remainder of the show uses non-zero season numbers.

Likewise, S03E00 is common for labeling a pre-season "recap" special..

While all these cases don't make much of a difference for live TV, as we implement support for Android N's recording functionality, they become more important to ensure everything is grouped correctly etc.

All that said - those episodes in the TVH screenshot appear to show that TVHeadend is aware that the content is seasonless, which TVH might have a way to tell us about, can you grab a sample from the JSON API for one of those episodes?

1. Find the channel UUID: Open http://tvheadend:9981/api/channel/grid?limit=5000 - find the channel and note it's channelUuid
2. Find the event itself: Open http://tvheadend:9981/api/epg/events/grid?channel=<CHANNEL-UUID>&limit=5000  - replacing <CHANNEL-UUID> with the ID you found in Step 1.
3. Search the content for the name of the show, copy and pate a few hundred characters on either side of the show name and paste here

**Comment by tunip** [comment]
This is more cosmetic and not really important. I will give you a few shows as an example.

This is all from XMLTV source (no OTA EPG).

Documentation
```
"start":1470218400,"stop":1470221100,"title":"Der Balkan Express","subtitle":"Slowenien","description":"Slowenien hat geografisch eine Menge zu bieten...","episodeNumber":1,"episodeOnscreen":"e01"
"start":1470304800,"stop":1470307500,"title":"Der Balkan Express","subtitle":"Mazedonien","description":"In Mazedonien kann der Reisende Seen aus der Urzeit…“,“episodeNumber":4,"episodeOnscreen":"e04"
"start":1470161100,"stop":1470164640,"title":"Ägypten - Die Wiege der Architektur","description":"Zweitelige Dokumentation über die bahnbrechende Architektur und die Baukunst des alten Ägyptens. Part 1","episodeNumber":1,"episodeOnscreen":"e01"
"start":1470164640,"stop":1470168360,"title":"Ägypten - Die Wiege der Architektur","description":"Zweitelige Dokumentation über die bahnbrechende Architektur und die Baukunst des alten Ägyptens. Part 2","episodeNumber":2,"episodeOnscreen":"e02"
```

Soap/Reality-show
```
"start":1470307800,"stop":1470311400,"title":"Köln 50667","description":"Biker Alex hat in seiner Traumstadt Köln...","episodeNumber":909,"episodeOnscreen":"e909"
"start":1470308700,"stop":1470310800,"title":"Angry Boys","description":"Die Hochzeit von Daniels und Nathans Mutter steht an.","episodeNumber":10,"episodeOnscreen":"e10"
```

Thx

**Comment by tunip** [comment]
I tried this myself. If i only set episodeNumber without a seasonNumber, episodeNumber is not shown in the Live Channels guide & infobar.

**Comment by tunip** [comment]
Think we can close this too. The main issue are resolved.
