### ISSUE TITLE
Standalone XMLTV client

### ISSUE THREAD

**Issue by kyvaith** [kiall/android-tvheadend#3]
Hi,

Is it possible to use it as standalone IPTV client? I have paid m3u8 list with m3u streems and xml epg. I would like to use it with Google Live Channels.

Thanks.

**Comment by kiall** [comment]
Nope, this is specifically for use with a TVHeadend server. That said - TVHeadend can take in IPTV / XMLTV content, so you may be able to do that... http://tvheadend.org/

**Comment by kyvaith** [comment]
Ok, but having TV with full Android operation system, I shouldn't need separate device just to proxy content from web.

**Comment by kiall** [comment]
Sure, but that's unrelated to this app, who's purpose is to provide satellite and terrestrial content into android TV devices which don't have satellite or terrestrial connections. There may be some other app which does what you want...
