### ISSUE TITLE
Support Recording

### ISSUE THREAD

**Issue by kiall** [kiall/android-tvheadend#33]
Support Recording

**Comment by Wob76** [comment]
This would be great :)

**Comment by stevellion** [comment]
naturally, this should trigger a recording on the central tvheadend, not on the client itself.

**Comment by kiall** [comment]
That's the plan, on top of that, I hope to be able to have recordings be shared between devices, 

Blocked on #32 which needs to land first, and is in progress.

**Comment by stevellion** [comment]
It shouldn't need any sharing between devices, as it's recorded centrally on the TVheadend server, it'll therefore automatically be available to all.
Which is the other question though ; How to access previously recorded material stored on TVH.

**Comment by kiall** [comment]
Android needs us to tell it about each recording, so when 1 device records, all need to be informed.. otherwise, they won't show the recording.

Android has many permissions which aren't granted to non-system apps. For example, we can only add channels in response to direct user input. We can't do it in the background. If this same measure applies to recordings, sharing between devices will not be possible.

**Comment by stevellion** [comment]
Hmm. maybe some kind of seperate UI to access recorded material?
(I'm using Kodi as a base, all my other TV's in the house have Kodi boxes instead of TV Antennas)
I was thinking if can present Recordings as a channel, but I think it makes more sense as a browse/select type gui to play the recordings.  Would that be easier than trying to cross-device calls?

**Comment by xi784** [comment]
interesting, which means that we also can´t get epg eventupdates live?

**Comment by kiall** [comment]
EPG updates are allowed, channel additions are not..

I'm (currently) unsure about DVR entries... Hopefully they are allowed, but we'll see.

**Comment by kiall** [comment]
The base changes for this have landed in the develop branch and will be released soon..
