### ISSUE TITLE
Support Homescreen Recommendations

### ISSUE THREAD

**Issue by kiall** [kiall/android-tvheadend#37]
Repored on G+ here https://plus.google.com/105543723922836246512/posts/ESMLELciCfA

**Comment by tunip** [comment]
If you implement poster artwork you have automatically homescreen recommendations from Live Channels app.

**Comment by kiall** [comment]
Fixed in #42

**Comment by tunip** [comment]
Found a bug. We need something more in the SyncAdapter.java to update recommendations.

**Comment by tunip** [comment]
Had a second app (robotv for VDR) installed. If I remove this app from Android TV device, recommendations not updated for Tvheadend app.

**Comment by tunip** [comment]
Recommendations are updated now. Will test it a few days before I do a PR.

**Comment by kiall** [comment]
Nice, I'd love to get the PR in and I'll push a release :)

**Comment by tunip** [comment]
Can we close this issue?

**Comment by kiall** [comment]
Yep, forgot about closing it :)
