### ISSUE TITLE
Missing EPG Data.

### ISSUE THREAD

**Issue by Wob76** [kiall/android-tvheadend#40]
For some reason tonight I keep loosing EPG data from some of my channels, usually all from a single mux. 

I have force closed the TVHeadend and Live Channel apps and the problem persists.

I reran the setup for TVHeadend app, and the data started showing from the first mux\channels I was having issues with, but at the same time I lost EPG for a different mux\channels.

rerunning setup again made no difference..

My EPG data is OTA data pulled from the muxes.
All Channels have EPG data on the tvheadend server.
Channel Icons are working for the problem channels.

No errors on the tvheadend server.

Let me know if I can do anything to help diagnose.

**Comment by Wob76** [comment]
Oh, for scale, I have 21 TV channels and 5 audio only channels, the audio do not pull into TVHeadend App. These come from 5 DVB-T muxes.

**Comment by kiall** [comment]
Interesting. I've not seen this before, even with hundreds of channels. Could you try record the device logs during an EPG sync? Googling for <device name> + adb logcat should get you the instructions for your device, then open the settings app, go to the TVH account, and trigger a sync. Once it completes, trigger a second sync ASAP so I can see the count of added/changed/removed etc in a short period.

Also - Try doing this at an "odd" time, e.g. 17mins past the hour - where shows are less likely to have finished between the first and second sync!

**Comment by kiall** [comment]
The whole EPG code has now been replaced, whatever this issue was, it's gone.. (or replaced by a different issue). Closing this out...
