### ISSUE TITLE
Cannot Download for MXQ andorid TVBox

### ISSUE THREAD

**Issue by bebekbalap** [kiall/android-tvheadend#41]
Hallo my fren

it cannot download for MXQ androidbox ?
![img_20160918_071904](https://cloud.githubusercontent.com/assets/22274847/18615666/ff302c46-7dde-11e6-95f5-2d84a774c6e8.jpg)

Thanks

**Comment by kiall** [comment]
The app requires Android TV from Google, the MXQ isn't Android TV, it's Android, hooked up to a TV, but doesn't include any of Googles Android TV software. Many of the "Android TV" boxes are really just misleading marketing.. sorry!

**Comment by bebekbalap** [comment]
its OK : )
