### ISSUE TITLE
Automatic refresh rate switching

### ISSUE THREAD

**Issue by kiall** [kiall/android-tvheadend#52]
Some devices supported automatic refresh rate switching, identify how this app can/should interact with this, and implement it.

nVidia Shield is one such device.

**Comment by kiall** [comment]
Reported at G+ here https://plus.google.com/107864640890603414630/posts/BFnZtdkzND3

**Comment by stevenwhately** [comment]
Nexus player has automatic refresh rate switching.
Chromecast has 50Hz mode.
https://support.google.com/chromecast/answer/6308937?hl=en-AU

**Comment by wrxtasy** [comment]
WeTek Play2 with this ATV OS ROM image that works well with Live Channels and TvHeadend Beta for 25/50fps deinterlacing and full auto Android Global App refresh switching (any Android App, eg. 24p Netflix):

http://wetekforums.com/v/index.php?p=/discussion/28822/rom-weos-1-3-based-android-tv-v1-0/p1

Basically you need to buy a device that implements this autoswitching in the Kernel itself.
This is not a TvHeadend beta problem.

**Comment by stevenwhately** [comment]
In countries that broadcast in 25/50Hz, users don't want to see screen taring caused by TV's running at 60Hz.
Kodi automatically sets the refresh rate to 50Hz when playing this content.
So for all non WeTek Play2 users, we need either a simple 50Hz setting or automatic refresh rate switching.

**Comment by wrxtasy** [comment]
As feedback for this.  A Android TV - Xiaomi Mi Box running Android Marshmallow does not have any working refresh rate switching. However it does have a new AMLogic Kernel setting - HDMI Adaptation.  

Whatever tricks they are using in the video drivers and timers produces good results. Even 25/50fps content such as TV output at a fixed 1080p60hz is surprisingly great for everything apart from fast action sports where very minor judder can be detected if you look hard.

**Comment by kiall** [comment]
Some links on this

* Current display mode: https://developer.android.com/reference/android/view/Display.html#getMode()
* List of available modes: https://developer.android.com/reference/android/view/Display.html#getSupportedModes()
* Set current mode: https://developer.android.com/reference/android/view/WindowManager.LayoutParams.html#preferredDisplayModeId

Nabbed from https://github.com/JamesLinEngineer/RKMC/issues/8

**Comment by gazzer82** [comment]
This would be incredibly useful!

Cheers

Gareth

**Comment by gazzer82** [comment]
As to follow up, I generally have my shield set to 59.94Hz as Netflix and several other apps seem to work best at that refresh rate.

I have refresh rate switching enabled in Kodi so when I watch UK TV it switches to 50hz to prevent the 25fps/30fps judder.

Works well and would be great to see this in Live Channels TvHeadend.

Cheers

Gareth

**Comment by kiall** [comment]
Note that, the Live Channels app itself is the only thing that can switch the framerate, and it's currently hardcoded to only switch for 24fps content: https://android.googlesource.com/platform/packages/apps/TV/+/79f2e98d97cde644bb1b0327a4d3bfeaf8dde8c7/src/com/android/tv/MainActivity.java#2155

I've tested going from 25fps, to 24fps content and my display switches to 24Hhz.. Once I return to 25fps content, the display goes back to 60Hhz. I've no control over this sadly.

**Comment by kiall** [comment]
Reported to Google - https://code.google.com/p/android/issues/detail?id=248102

Hopefully an update and some point will enable refresh rate switching for more than just 24fps content.

**Comment by kiall** [comment]
Since Googles old issue tracker is gone, I re filed that issue on the new one @ https://issuetracker.google.com/issues/63734428
