### ISSUE TITLE
HTSP Video Playback

### ISSUE THREAD

**Issue by kiall** [kiall/android-tvheadend#56]
Use HTSP to handle video Playback

**Comment by snoopy86** [comment]
It HSTP playback available for testing?

**Comment by kiall** [comment]
@snoopy86 the latest builds have an option to turn it on, but it really isn't ready for primetime yet!

**Comment by kiall** [comment]
As the basics of this is done + working, I'm calling this closed... There is still pile of issues, but they can be handled separately.
