### ISSUE TITLE
java.lang.RuntimeException: Package manager has died

### ISSUE THREAD

**Issue by xi784** [kiall/android-tvheadend#77]
Hi Kiall,

no idea whether this is helpful, search for "AndroidRuntime", there are some fatal error.

[logcat - 48.zip](https://github.com/kiall/android-tvheadend/files/560453/logcat.-.48.zip)

**Comment by kiall** [comment]
The actual crash part of this:

	--------- beginning of crash

	10-29 00:26:03.213  3187  6321 E AndroidRuntime: FATAL EXCEPTION: Thread-1132
	10-29 00:26:03.213  3187  6321 E AndroidRuntime: Process: ie.macinnes.tvheadend, PID: 3187
	10-29 00:26:03.213  3187  6321 E AndroidRuntime: java.lang.RuntimeException: Package manager has died
	10-29 00:26:03.213  3187  6321 E AndroidRuntime:        at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:134)
	10-29 00:26:03.213  3187  6321 E AndroidRuntime:        at ie.macinnes.tvheadend.MiscUtils.getAppVersionName(MiscUtils.java:32)
	10-29 00:26:03.213  3187  6321 E AndroidRuntime:        at ie.macinnes.tvheadend.sync.EpgSyncService.initHtspConnection(EpgSyncService.java:138)
	10-29 00:26:03.213  3187  6321 E AndroidRuntime:        at ie.macinnes.tvheadend.sync.EpgSyncService.openConnection(EpgSyncService.java:117)
	10-29 00:26:03.213  3187  6321 E AndroidRuntime:        at ie.macinnes.tvheadend.sync.EpgSyncService$2.onStateChange(EpgSyncService.java:162)
	10-29 00:26:03.213  3187  6321 E AndroidRuntime:        at ie.macinnes.htsp.Connection.setState(Connection.java:330)
	10-29 00:26:03.213  3187  6321 E AndroidRuntime:        at ie.macinnes.htsp.Connection.open(Connection.java:188)
	10-29 00:26:03.213  3187  6321 E AndroidRuntime:        at ie.macinnes.htsp.Connection.run(Connection.java:103)
	10-29 00:26:03.213  3187  6321 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
	10-29 00:26:03.213  3187  6321 E AndroidRuntime: Caused by: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
	10-29 00:26:03.213  3187  6321 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
	10-29 00:26:03.213  3187  6321 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:503)
	10-29 00:26:03.213  3187  6321 E AndroidRuntime:        at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:2216)
	10-29 00:26:03.213  3187  6321 E AndroidRuntime:        at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:129)
	10-29 00:26:03.213  3187  6321 E AndroidRuntime:        ... 8 more

**Comment by xi784** [comment]
Kiall take a look on this:

10-30 12:15:00.914 23774 23774 E UncaughtException: java.lang.IllegalArgumentException: redundant track ID: 0-771
