### ISSUE TITLE
Logcat errors during EPG updates

### ISSUE THREAD

**Issue by cyberjacob** [kiall/android-tvheadend#82]
When updating the EPG, the following error repeats in the logs:

    11-01 10:42:49.061 15181-16513/ie.macinnes.tvheadend E/ie.macinnes.htsp.tasks.GetFileTask: Error handling a GetFileTask message
    11-01 10:42:49.061 15181-16513/ie.macinnes.tvheadend W/ie.macinnes.tvheadend.sync.EpgSyncTask: Failed to fetch logo for content://android.media.tv/channel/203
    11-01 10:42:49.068 15181-16513/ie.macinnes.tvheadend E/ie.macinnes.htsp.tasks.GetFileTask: Error handling a GetFileTask message
    11-01 10:42:49.068 15181-16513/ie.macinnes.tvheadend W/ie.macinnes.tvheadend.sync.EpgSyncTask: Failed to fetch logo for content://android.media.tv/channel/205

This appears to repeat for each tvheadend channel. Channel logos show as normal, so I'm guessing this is related to the show logos?

EDIT: These are "correct", in that TVH believes there is a logo, but it doesn't actually exist. We should make this cleaner, and maybe stat the logo before attempting to open it.

**Comment by kiall** [comment]
Usually, this is related to channels that don't have a logo. TVHeadend tells us every channel does, but it's a lie.

Do all channels have logos? If some don't, I'll bet the # of errors lines up with the number of channels without logos.

**Comment by kiall** [comment]
(though, we should change this to log a better message...)

**Comment by cyberjacob** [comment]
Do the channel numbers in the android media URI (123 in `content://android.media.tv/channel/123`) correspond with the channel numbers in TVHeadend? If so, then I don't have channels with the numbers in the errors.

I do have some channels without logos, though the error isn't showing up for those.

**Comment by kiall** [comment]
No, the numbers don't line up. Android picks the `content://android.media.tv/channel/123` ID, and it's unrelated to the channel display number.

**Comment by cyberjacob** [comment]
Ah, then that could explain it. I'll try filling in some dummy images and see if the errors disappear

**Comment by cyberjacob** [comment]
Gone through all my channels in TVHeadend, and with the exception of one, they all have channel logos assigned. However a large portion (about 1/4-1/3) aren't being displayed. This seems to correspond with icons that don't show in TVHeadend's web interface.

**Comment by kiall** [comment]
So, to confirm, TVH's UI and Live Channels show the same set of icons, and a number of channels with icons assigned don't show in both TVH UI and Live Channels?

**Comment by cyberjacob** [comment]
Yup, I'm guessing that means it's a configuration issue or bug in TVH?

**Comment by kiall** [comment]
Yea, either the configured logo URLs/files don't exist, or they are corrupt etc.

If your using tvheadend's "picos" support, then it configures a file for every channel, even if there isn't a matching picon.

I'll leave this open, even if it's just to make the message clearer.
