### ISSUE TITLE
Recommendations do not display

### ISSUE THREAD

**Issue by cyberjacob** [kiall/android-tvheadend#89]
I'm not seeing any recommendations appear for any tvheadend channels. I've confirmed that the EPG data is populated.

I think this may be caused by a lack of show images in the EPG data, as the issue to get recommendations working in the first place mentioned it.

**Comment by kiall** [comment]
Correct, without episode images, Android will not show a recommendation.

I'm not sure there is really anything that can be done, bar putting fake images in (maybe the channel logo), bit this would make the EPG view a mess, and would annoy people to no end!

**Comment by tunip** [comment]
You need a XMLTV file as EPG source for Tvheadend with "icon src=" like this:
```
...
  <programme start="20161108135000 +0100" stop="20161108145000 +0100" channel="kabel eins HD">
    <title lang="de">The Mentalist</title>
    <sub-title lang="de">Auftragsmord</sub-title>
    <desc lang="de">Die stellvertretende Bezirksstaatsanwältin Flower liegt erschossen in ihrer Wohnung. Ein "Auftragsmord" – Mentalist Jane (Simon Baker) weiß zwar nach wenigen Minuten, wer der Killer ist. Aber wer hat ihn beauftragt? Verdächtig ist Drogenschmuggler Draber (John Kapelos).</desc>
    <credits>
      <director>Adam Kane</director>
      <actor>Simon Baker</actor>
      <actor>Robin Tunney</actor>
      <actor>Tim Kang</actor>
      <actor>Owain Yeoman</actor>
      <actor>Amanda Righetti</actor>
      <actor>Aunjanue Ellis</actor>
      <actor>John Kapelos</actor>
    </credits>
    <date>2010</date>
    <category>Soap/Melodrama/Folkloric</category>
    <icon src="http://live.tvspielfilm.de/static/images/broadcasts/952/54ad1603e4b0c014707243ca.jpg" />
    <country>USA</country>
  </programme>
...
```

Without that, you will not have artwork in the guide and no recommendation on homescreen.

@kiall Maybe in the future we can search something like TheMovieDB/TheTVDB for artwork.

**Comment by kiall** [comment]
@tunip that's not a bad idea, though it would cause EPG sync to become slower/more work, as every episode would end up making API calls out to TVDB etc. They could be queued to happen in the background. Theres also bound to be rate limits on TVDB/TheMovieDB's APIs. These are normally (as far as I know) used by things like Plex or Kodi for downloaded content, the number of episodes that would need to be queried for say a week of OTA satellite would be monstrous in comparison for those of us with lots of channels.

Some googling suggests 1 API call per 2 seconds to TVDB, while the MovieDB seems to be 30 per 10 seconds per IP (So, if you have 2-3 TVs running the app like I do, it drops to less...)

**Comment by tunip** [comment]
@kiall you could minimize a little bit the requets by a minimum and maximum event duration:

movie duration>='65' (search/fetch artwork from MovieDB if event is equal or longer than 65 minutes)
tvshow duration >='25' & duration<='65' (search/fetch for TVDB-ID from MovieDB if event is between 25-65 minutes, fetch external TVDB-ID and then fetch artworkt data from TVDB)

You can filter out a lot of short events like news, weather, short magazines with durations.
Some short kids shows can't be fetched in this case. But the values could be a settings value.

**Comment by seapoint** [comment]
Why not just have http://www.webgrabplus.com/ run on your TVHeadend server?

**Comment by kiall** [comment]
Yea, given there is often multiple TVs etc.. It's probably best to just do it on the server, once for all TVs etc...

**Comment by cyberjacob** [comment]
@tunip any idea where I can get one of those for UK freeview/freesat? Kodi manages to get them from somewhere...

**Comment by tunip** [comment]
@cyberjacob you can use WebGrab+Plus with one or more of these ini's http://www.webgrabplus.com/epg-channels#stc_4D.

e.g.: freesat.co.uk is a good start.

I extended the freesat.co.uk ini with artwork (3 additional lines)

Result with "icon src" now:
```
  <programme start="20161108190000 +0000" stop="20161108200000 +0000" channel="Channel 5 HD">
    <title lang="en">Police Interceptors</title>
    <desc lang="en">Hoppsy goes after a disqualified driver who legs it over two fences, Damo gets his stinger out to stop a drunk driver and Kev solves the mystery of a car abandoned in a field</desc>
    <icon src="http://fdp-sv15-image-v1-0.gcprod1.freetime-platform.net/cache/1366x766-2/ms/img/epg/rb/16352513.l.jpg" />
  </programme>
```

**Comment by cyberjacob** [comment]
@tunip strange, looks like my view of the comments page hadn't updated properly when I posted that (last commend I could see was your first one)

I've just managed to get WebGrab+Plus up and running with data from metabroadcast. It's taking a while for the initial sync, but I'll let you know what happens afterwards.

**Comment by seapoint** [comment]
I actually find the TVGuide.co.uk to be a more comprehensive guide, includes all free & encrypted for sat/terrestrial for UK/Ireland. Their default ini works straight off , just need to collect a cookie.

**Comment by cyberjacob** [comment]
So after letting the EPG sync with images, I'm now getting reccomendations
