### ISSUE TITLE
Sony: Sorting channels

### ISSUE THREAD

**Issue by snoopy86** [kiall/android-tvheadend#92]
Hi,

was sorting of channels changed? Because now it doesn't sort them by channel number or by name. They are sorted in not normal pattern, something random.

I tried sorting by number and name but it doesn't make a difference.

Version is: v0.2.54-3-g27b299e

**Comment by tunip** [comment]
Nothing changed here. Channel order by numbers works fine.

**Comment by kiall** [comment]
So - I'm betting @snoopy86 is using a Sony Android TV? They have a bug where the EPG view will display channels based upon the order in which they were added. 

This is simply broken! As new channels are added, with a middle channel number, there is no way to have it sort correctly other than to delete all channels, and re-add them all again.

Sony needs to fix this :(

**Comment by snoopy86** [comment]
Yes i have sony android tv.

**Comment by Satmario** [comment]
Hi,

same problem om my Sony Android TV. The previous build was OK.

**Comment by kiall** [comment]
I'm stumped - can't find any way to make Sony sets correctly and permanently sort the channels.

Attempting to reach out to Sony via https://plus.google.com/115557954602502982039/posts/Am5crFwVz8a?sfc=true

**Comment by stevellion** [comment]
Apologies if this is a daft question, but have you been on this site?
https://developer.sony.com/develop/tvs/

**Comment by kiall** [comment]
I have, there's not much there other than links to the Android docs..

**Comment by kiall** [comment]
Let's see if Twitter leads to someone from Sony - https://twitter.com/kiall/status/820748494734561281

**Comment by kiall** [comment]
(If someone from Sony does pop by, the Google+ post linked above has the best written explanation of the bug...)

**Comment by stevellion** [comment]
As an ugly workaround, can you import the channels in forced sequence? Like import channel by channel in a for loop?

**Comment by stevellion** [comment]
Just to confirm.. I switched back to my build of 0.1.40  and this channel sorting issue doesn't exist.
I figure there is a different way that you import the channels etc in the 0.2.x versions?
Is it not possible to use the old way of channel import on Sony's?

**Comment by kiall** [comment]
We can sort them, once. As new channels pop up, the bug will show itself again.. even on 0.1.40.

I was hoping to avoid putting a Sony specific hack into the code, but as I can't manage to find any way to report Android TV issues to Sony, I guess we've got no choice.

When new channels are added, the only FX for Sony will be to uninstall and reinstall the app from scratch to re-sort the channels :(

**Comment by stevellion** [comment]
No way or sorting/re-importing once every 24 hours? - say 4am or something?

**Comment by kiall** [comment]
Nope, well, yes.. we could delete all and re-add them, but Android will mark them as hidden until the user explicitly chooses to show them again, it would basically look like all the channels have just disappeard. Either there's a workaround I can use, or Sony needs to fix their implementation of Live Channels for a full+permanent fix.

**Comment by Satmario** [comment]
Any chance to download the 0.1.40 build as apk ?

Thanks :)

**Comment by kiall** [comment]
I don't personally have it anymore, if someone doea, send it to me and I'll put it on the GitHub releases page.

**Comment by stevellion** [comment]
I built a 0.1.40 version which runs fine on my Sony Bravia Android 6.0.1 TV...  https://dl.dropboxusercontent.com/u/49011675/tvheadend-live-1-40.apk

**Comment by stevellion** [comment]
Can we go with the workaround / pre 2.0 method please.. - because without sorting it's pretty much unusable.  In reality, channels get added infrequently, so if there really was a channel needed before a Sony fix - then it just needs a reinstall.

**Comment by kiall** [comment]
Yea, as soon as find the time I'll add a workaround :)

**Comment by stevellion** [comment]
Cool. I see you generally only update at the weekends.  :-)  - PS - I just posted this on the Sony community website, see if anyone responds.: https://community.sony.co.uk/t5/android-tv/where-do-we-get-developer-support-for-android-tv-app-sony/m-p/2288958#M15809

**Comment by Satmario** [comment]
Also on my Sony Android TV V 0.1.4O works fine :) and the initial setup is is more faster like the last build....

**Comment by kiall** [comment]
Included in v0.2.87

**Comment by ghost** [comment]
> I built a 0.1.40 version which runs fine on my Sony Bravia Android 6.0.1 TV... https://dl.dropboxusercontent.com/u/49011675/tvheadend-live-1-40.apk

This link doesn't work. Where can I download the latest version?
