### ISSUE TITLE
No AC3 audio with VLC player

### ISSUE THREAD

**Issue by crazy888** [kiall/android-tvheadend#93]
Watching a channel with Codec: A52 Audio (aka AC3) (a52 ) does not output any audio.

Channels with Codec: MPEG Audio layer 1/2 (mpga) are running fine.

Hardware:
Nvidia Shield 16GB
Player VLC

Edit: I will deliver some logs, but connecting with ADB to Nvidia Shield makes problems. Working on it!

**Comment by kiall** [comment]
VLC is in the process of being removed, and replaced with a full featured ExoPlayer (Google's Android media library) based setup. Test builds for this already have AC3 audio and passthrough working. It'll be published to the beta group on the Play Store soon, and the test build APKs are already linked from https://plus.google.com/communities/102705346691784371187

**Comment by kiall** [comment]
The VLC+MediaPlayer session types are being deprecated in favor of ExoPlayer, please try ExoPlayer, using a MKV stream profile, on v0.1.66 or newer - if there issue is present there, please open a new bug. (Bulk close of non-ExoPlayer issues)
