### ISSUE TITLE
Green beam on the right side

### ISSUE THREAD

**Issue by antropy42** [kiall/android-tvheadend#94]
Hi,
i love this app. now my sony androidtv works really well. This app is awesome, great work guys.
But i see on the right side of the SD Picture a small green or violett beam. In HD Channels the beam disappears and the picture is absolutly great.

I think i know this behaviour from emby with my earlier firetv. there it was an issue with vlc. So i tried to change the player, but the other two players not working here. No Sound and Picture with the exo player and the media player raises an error.

I think that is a bug, what do you think?

kind regards
tom

**Comment by tunip** [comment]
We are in the move to HTSP also for the video (EPG part is done already).
This will change a lot in this area. So please be patient until this part is finished.

**Comment by kiall** [comment]
Can you try v0.2.66 (check the GitHub release page for an APK download, or if your in the beta group, it'll be on the play store). With it, try ExoPlayer again. On TVHeadend, change your "tif" stream profile to be a MKV profile.

The ExoPlayer session has gone through some major rework, and will soon be the only choice with VLC etc removed.

**Comment by kiall** [comment]
The VLC+MediaPlayer session types are being deprecated in favor of ExoPlayer, please try ExoPlayer, using a MKV stream profile, on v0.1.66 or newer - if there issue is present there, please open a new bug. (Bulk close of non-ExoPlayer issues)
